// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./src/test/proto/test.proto
package com.levelmoney.kbuilders.test.proto;

import com.squareup.wire.ProtoEnum;

public enum AddressType
    implements ProtoEnum {
  RESIDENTIAL(1),
  BUSINESS(2);

  private final int value;

  private AddressType(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
